# Generated by Django 4.1.7 on 2023-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
